### ISSUE TITLE
[segment-download] Downloading some files results in download failure

### ISSUE THREAD

**Issue by Soniczac7** [Download-Manager-Community/Download-Manager#96]
### Describe the bug

Downloading certain files such as GitHub source code zip files results in the exception:
```
The From or To parameter cannot be less than 0. (Parameter 'to') (System.ArgumentOutOfRangeException)
   at System.Net.HttpWebRequest.AddRange(String rangeSpecifier, Int64 from, Int64 to)
   at System.Net.HttpWebRequest.AddRange(Int64 from, Int64 to)
   at DownloadManager.DownloadProgress.DownloadFileAsync(Uri uri, CancellationToken cancellationToken, Action`3 progressCallback, BetterProgressBar progressBar) in E:\Download Manager\DownloadManager\DownloadProgress.cs:line 1340
   at DownloadManager.DownloadProgress.StartNormalDownload() in E:\Download Manager\DownloadManager\DownloadProgress.cs:line 1146
```

### Steps to reproduce

This process does not work for all files. Files that it does work with are GitHub source code zip files.
1. Download a file using a download manager
2. See exception

### Expected behaviour

The file should download normally.

### Download Manager Version

Latest segment-download (0946f2d)

### Windows Version

Windows 11 Pro Insider Preview 22H2 23565.1000

### Comments

It looks like it is caused by the content length being returned as -1 which would mean that progress reporting is not available.
Because no progress reporting has yet been implemented in the new downloading system this error occurs.

**Comment by Soniczac7** [comment]
Fixed in 76cb3dc
